sudo: required
dist: trusty
language: node_js
node_js:
  - "8.9.1"
os:
  - linux
before_install:
  # Use a virtual display.
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  # Install latest chrome.
  - export CHROME_BIN=chromium-browser
install:
  - npm install
script:
  - npm run lint
  - ng test --single-run
